### ISSUE TITLE
Fresh failing to rebuild code

### ISSUE THREAD

**Issue by andysbolton** [DarthHater/bored-board-service#18]
Hey, I've been having some trouble with `fresh` the last couple weeks and just wanted to verify that it is working correctly for you @DarthHater. If I do a fresh clone on the repo and `docker-compose up`, everything goes smooth and `fresh` starts running but will fail with a `go install github.com/darthhater/bored-board-service: open tmp/runner-build: no such file or directory` error on rebuild (that file does exist but is not accessible for some reason). If I do a clone on [this git repo](https://github.com/McMenemy/GoDoRP) that uses fresh and docker compose it seems to work fine. I've went down a few avenues to solve this but mostly just wanted to check to make sure it's working for you.

**Comment by DarthHater** [comment]
I'll take a gander at this tomorrow. Sorry for being a bit absent, I bought a house and it's been consuming a bit of my life.

**Comment by andysbolton** [comment]
This appears to be a bug in the library, gonna go ahead and close it for now.
