### ISSUE TITLE
IMPLEMENT: Return entire Post object on POST create of Post (Lol POST!)

### ISSUE THREAD

**Issue by DarthHater** [DarthHater/bored-board-service#24]
After some thinking and consultation with a couple friends, rather than just returning the ID, we should return the entire `post` object as a part of creation. This greatly simplifies things on the front end, as we will be able to just take that and pop it into the store, and from what I know follows better practices in terms of what is expected from a REST POST endpoint.

**Comment by andysbolton** [comment]
This one should be included in #21 now.
