### ISSUE TITLE
IMPLEMENT: The ability to edit a post

### ISSUE THREAD

**Issue by DarthHater** [DarthHater/bored-board-service#8]
I think for this feature what we would ideally like:

* Posts should be editable within a specific time period, by the user who submitted them (let's say X minutes, for typos?)
* Posts should be editable for admin/mods for all of eternity

**Comment by andysbolton** [comment]
I might take this one for a ride.

**Comment by DarthHater** [comment]
@andysbolton I've been on a Redux adventure on the front end, but if you wanted to pick this one up, I'll be swinging back to the service soon.

**Comment by andysbolton** [comment]
@DarthHater Okay, sweet, I have a bit of this one done and can push it in a little while.

**Comment by andysbolton** [comment]
Should be covered off in #21.
